/* tslint:disable */
/* eslint-disable */
/**
 * Rick and Morty API
 * Access information about characters from Rick and Morty.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Character } from './Character';
import {
    CharacterFromJSON,
    CharacterFromJSONTyped,
    CharacterToJSON,
    CharacterToJSONTyped,
} from './Character';
import type { CharacterListResponseInfo } from './CharacterListResponseInfo';
import {
    CharacterListResponseInfoFromJSON,
    CharacterListResponseInfoFromJSONTyped,
    CharacterListResponseInfoToJSON,
    CharacterListResponseInfoToJSONTyped,
} from './CharacterListResponseInfo';

/**
 * 
 * @export
 * @interface CharacterListResponse
 */
export interface CharacterListResponse {
    /**
     * 
     * @type {CharacterListResponseInfo}
     * @memberof CharacterListResponse
     */
    info?: CharacterListResponseInfo;
    /**
     * 
     * @type {Array<Character>}
     * @memberof CharacterListResponse
     */
    results?: Array<Character>;
}

/**
 * Check if a given object implements the CharacterListResponse interface.
 */
export function instanceOfCharacterListResponse(value: object): value is CharacterListResponse {
    return true;
}

export function CharacterListResponseFromJSON(json: any): CharacterListResponse {
    return CharacterListResponseFromJSONTyped(json, false);
}

export function CharacterListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CharacterListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'info': json['info'] == null ? undefined : CharacterListResponseInfoFromJSON(json['info']),
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(CharacterFromJSON)),
    };
}

export function CharacterListResponseToJSON(json: any): CharacterListResponse {
    return CharacterListResponseToJSONTyped(json, false);
}

export function CharacterListResponseToJSONTyped(value?: CharacterListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'info': CharacterListResponseInfoToJSON(value['info']),
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(CharacterToJSON)),
    };
}

