/* tslint:disable */
/* eslint-disable */
/**
 * Rick and Morty API
 * To API pozwala uzyskiwać informacje o bohaterach serialu Rick and Morty.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CharactersResponse,
} from '../models/index';
import {
    CharactersResponseFromJSON,
    CharactersResponseToJSON,
} from '../models/index';

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Pobierz postacie serialu Rick And Morty
     */
    async getCharacterRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CharactersResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/character`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CharactersResponseFromJSON(jsonValue));
    }

    /**
     * Pobierz postacie serialu Rick And Morty
     */
    async getCharacter(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CharactersResponse> {
        const response = await this.getCharacterRaw(initOverrides);
        return await response.value();
    }

}
