openapi: 3.0.0
info:
  title: Amazing API
  description: API for retrieving various resources such as authors and articles
  version: 1.0.0
servers:
  - url: http://localhost:3000/api/data
    description: Development server
paths:
  /articles:
    get:
      summary: Retrieve a list of articles
      responses:
        '200':
          description: A list of articles
          content:
            application/json:
              schema:
                type: object
                properties:
                  articles:
                    type: array
                    items:
                      $ref: '#/components/schemas/Article'
components:
  schemas:
    Article:
      type: object
      properties:
        id:
          type: integer
          example: 1
        author:
          type: string
          example: 'John Doe'
        title:
          type: string
          example: 'Introduction to API'
        content:
          type: string
          example: 'This is the content of the article.'
