/* tslint:disable */
/* eslint-disable */
/**
 * Rick and Morty API
 * Access information about characters from Rick and Morty.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CharacterListResponse,
} from '../models/index';
import {
    CharacterListResponseFromJSON,
    CharacterListResponseToJSON,
} from '../models/index';

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Get a list of characters
     */
    async getCharactersRaw(params?: { name?: string; gender?: string; page?: number }, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CharacterListResponse>> {
        const queryParameters: any = {};

        if (params?.name) {
            queryParameters['name'] = params.name;
        }
    
        if (params?.gender) {
            queryParameters['gender'] = params.gender;
        }
    
        if (params?.page) {
            queryParameters['page'] = params.page;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/character`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CharacterListResponseFromJSON(jsonValue));
    }

    /**
     * Get a list of characters
     */
    async getCharacters(
        params?: { name?: string; gender?: string; page?: number },
        initOverrides?: RequestInit | runtime.InitOverrideFunction
      ): Promise<CharacterListResponse> {
          const response = await this.getCharactersRaw(params, initOverrides);
          return await response.value();
      }
      

}
