/* tslint:disable */
/* eslint-disable */
/**
 * Rick and Morty API
 * To API pozwala uzyskiwać informacje o bohaterach serialu Rick and Morty.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CharactersResponseInfo
 */
export interface CharactersResponseInfo {
    /**
     * Całkowita liczba postaci
     * @type {number}
     * @memberof CharactersResponseInfo
     */
    count?: number;
    /**
     * Liczba stron z wynikami
     * @type {number}
     * @memberof CharactersResponseInfo
     */
    pages?: number;
    /**
     * URL do następnej strony z wynikami (jeśli istnieje)
     * @type {string}
     * @memberof CharactersResponseInfo
     */
    next?: string | null;
    /**
     * URL do poprzedniej strony z wynikami (jeśli istnieje)
     * @type {string}
     * @memberof CharactersResponseInfo
     */
    prev?: string | null;
}

/**
 * Check if a given object implements the CharactersResponseInfo interface.
 */
export function instanceOfCharactersResponseInfo(value: object): value is CharactersResponseInfo {
    return true;
}

export function CharactersResponseInfoFromJSON(json: any): CharactersResponseInfo {
    return CharactersResponseInfoFromJSONTyped(json, false);
}

export function CharactersResponseInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CharactersResponseInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'] == null ? undefined : json['count'],
        'pages': json['pages'] == null ? undefined : json['pages'],
        'next': json['next'] == null ? undefined : json['next'],
        'prev': json['prev'] == null ? undefined : json['prev'],
    };
}

export function CharactersResponseInfoToJSON(value?: CharactersResponseInfo | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
        'pages': value['pages'],
        'next': value['next'],
        'prev': value['prev'],
    };
}

