/* tslint:disable */
/* eslint-disable */
/**
 * Amazing API
 * API for retrieving various resources such as authors and articles
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ArticlesGet200Response,
} from '../models/index';
import {
    ArticlesGet200ResponseFromJSON,
    ArticlesGet200ResponseToJSON,
} from '../models/index';

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Retrieve a list of articles
     */
    async articlesGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ArticlesGet200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/articles`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ArticlesGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Retrieve a list of articles
     */
    async articlesGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ArticlesGet200Response> {
        const response = await this.articlesGetRaw(initOverrides);
        return await response.value();
    }

}
